apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-system-ms-file-system-persistent-volume
  namespace: notes-project
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/file-system-ms-file-system
  storageClassName: standard