apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-persistent-volume
  namespace: notes-project
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/keycloak-postgres
  storageClassName: standard