apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-persistent-volume
  namespace: notes-project
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/rabbitmq
  storageClassName: standard