apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-persistent-volume
  namespace: notes-project
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/vault
  storageClassName: standard