kubectl create -f config-server-deployment.yaml
kubectl create -f file-system-ms-deployment.yaml
kubectl create -f file-system-ms-postgres-deployment.yaml
kubectl create -f kafka-deployment.yaml
kubectl create -f keycloak-deployment.yaml
kubectl create -f keycloak-postgres-deployment.yaml
kubectl create -f logic-ms-deployment.yaml
kubectl create -f logic-ms-postgres-deployment.yaml
kubectl create -f notes-admin-front-deployment.yaml
kubectl create -f notes-project-front-deployment.yaml
kubectl create -f pgadmin-deployment.yaml
kubectl create -f rabbitmq-deployment.yaml
kubectl create -f registration-ms-deployment.yaml
kubectl create -f registration-ms-front-deployment.yaml
kubectl create -f registration-ms-postgres-deployment.yaml
kubectl create -f user-data-ms-deployment.yaml
kubectl create -f user-data-ms-postgres-deployment.yaml
kubectl create -f zookeeper-deployment.yaml