apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-ms-deployment
  namespace: notes-project
  labels:
    app: logic-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logic-ms-deployment
  template:
    metadata:
      labels:
        app: logic-ms-deployment
    spec:
      containers:
        - name: logic-ms-deployment
          image: vlebediantsev/logic-ms
          ports:
            - containerPort: 8080
            - containerPort: 5005
          envFrom:
            - configMapRef:
                name: logic-ms-config-map