apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: notes-project
  labels:
    app: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-deployment
  template:
    metadata:
      labels:
        app: pgadmin-deployment
    spec:
      containers:
        - name: pgamind-deployment
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config-map