apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-ms-deployment
  namespace: notes-project
  labels:
    app: registration-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-ms-deployment
  template:
    metadata:
      labels:
        app: registration-ms-deployment
    spec:
      containers:
        - name: registration-ms-deployment
          image: vlebediantsev/registration-ms-final
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: registration-system-ms-config-map