apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: notes-project
spec:
  selector:
    app: config-server-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7777