kubectl create -f config-server-service.yaml
kubectl create -f file-system-ms-postgres-service.yaml
kubectl create -f file-system-ms-service.yaml
kubectl create -f kafka-service.yaml
kubectl create -f keycloak-postgres-service.yaml
kubectl create -f keycloak-service.yaml
kubectl create -f logic-ms-postgres-service.yaml
kubectl create -f logic-ms-service.yaml
kubectl create -f notes-admin-front-service.yaml
kubectl create -f notes-project-front-service.yaml
kubectl create -f pgadmin-service.yaml
kubectl create -f rabbitmq-service.yaml
kubectl create -f registration-ms-front-service.yaml
kubectl create -f registration-ms-postgres-service.yaml
kubectl create -f registration-ms-service.yaml
kubectl create -f user-data-ms-postgres-service.yaml
kubectl create -f user-data-ms-service.yaml
kubectl create -f zookeeper-service.yaml