apiVersion: v1
kind: Service
metadata:
  name: file-system-ms-service
  namespace: notes-project
  labels:
    app: file-system-ms-service
spec:
  selector:
    app: file-system-ms-deployment
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: file-system-ms-service-port