apiVersion: v1
kind: Service
metadata:
  name: file-system-ms-postgres-service
  namespace: notes-project
spec:
  selector:
    app: file-system-ms-postgres-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432