apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
  namespace: notes-project
spec:
  selector:
    app: keycloak-postgres-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432