apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: notes-project
  labels:
    app: keycloak-service
spec:
  selector:
    app: keycloak-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: keycloak-service-port
      nodePort: 31365