apiVersion: v1
kind: Service
metadata:
  name: logic-ms-service
  namespace: notes-project
  labels:
    app: logic-ms-service
spec:
  selector:
    app: logic-ms-deployment
  ports:
    - port: 80
      targetPort: 8070
      protocol: TCP
      name: logic-ms-service-port