apiVersion: v1
kind: Service
metadata:
  name: logic-ms-postgres-service
  namespace: notes-project
spec:
  selector:
    app: logic-ms-postgres-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432