apiVersion: v1
kind: Service
metadata:
  name: notes-project-front-service
  namespace: notes-project
  labels:
    app: notes-project-front-service
spec:
  selector:
    app: notes-project-front-deployment
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: notes-project-service-port