apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: notes-project
  labels:
    app: pgadmin-service
spec:
  selector:
    app: pgadmin-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: pgadmin-service-port
      nodePort: 31341