apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-admin-service
  namespace: notes-project
  labels:
    app: rabbitmq-admin-service
spec:
  selector:
    app: rabbitmq-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 15672
      name: rabbitmq-admin-service
      nodePort: 31367