apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: notes-project
  labels:
    app: rabbitmq-service
spec:
  selector:
    app: rabbitmq-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 5672
      name: rabbitmq-service
      nodePort: 31366
    - port: 81
      targetPort: 15672
      name: rabbitmq-admin
      nodePort: 31367