apiVersion: v1
kind: Service
metadata:
  name: registration-ms-front-service
  namespace: notes-project
  labels:
    app: registration-ms-front-service
spec:
  selector:
    app: registration-ms-front-deployment
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: registration-ms-front-service-port