apiVersion: v1
kind: Service
metadata:
  name: registration-ms-postgres-service
  namespace: notes-project
  labels:
    app: registration-ms-postgres-service
spec:
  selector:
    app: registration-ms-postgres-deployment
  ports:
    - port: 80
      targetPort: 5432
      protocol: TCP
      name: registration-ms-postgres-service-port