apiVersion: v1
kind: Service
metadata:
  name: registration-ms-service
  namespace: notes-project
  labels:
    app: registration-ms-service
spec:
  selector:
    app: registration-ms-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: registration-ms-service-port
      nodePort: 31369
    - port: 81
      targetPort: 5005
      protocol: TCP
      name: registration-ms-service-port-debug
      nodePort: 31345