apiVersion: v1
kind: Service
metadata:
  name: user-data-ms-postgres-service
  namespace: notes-project
spec:
  selector:
    app: user-data-ms-postgres-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432