apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: notes-project
  labels:
    app: vault-service
spec:
  selector:
    app: vault-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 8200
      protocol: TCP
      name: vault-service-port
      nodePort: 31364