apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: notes-project
  labels:
    app: zookeeper-service
spec:
  selector:
    app: zookeeper-deployment
  ports:
    - port: 80
      targetPort: 2181
      protocol: TCP
      name: zookeeper-service-port