apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-system-ms-postgres-persistent-volume-claim
  namespace: notes-project
spec:
  volumeName: file-system-ms-postgres-persistent-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi