apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data-ms-postgres-persistent-volume-claim
  namespace: notes-project
spec:
  volumeName: user-data-ms-postgres-persistent-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi