apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-persistent-volume-claim
  namespace: notes-project
spec:
  volumeName: vault-persistent-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi