kubectl create -f file-system-ms-config-map.yaml
kubectl create -f file-system-ms-postgres-config-map.yaml
kubectl create -f kafka-config-map.yaml
kubectl create -f keycloak-config-map.yaml
kubectl create -f keycloak-postgres-config-map.yaml
kubectl create -f logic-ms-config-map.yaml
kubectl create -f logic-ms-postgres-config-map.yaml
kubectl create -f notes-admin-front-config-map.yaml
kubectl create -f pgadmin-config-map.yaml
kubectl create -f rabbitmq-config-map.yaml
kubectl create -f registration-ms-front-config-map.yaml
kubectl create -f registration-ms-postgres-config-map.yaml
kubectl create -f registration-system-ms-config-map.yaml
kubectl create -f user-data-ms-config-map.yaml
kubectl create -f user-data-ms-postgres-config-map.yaml
kubectl create -f zookeeper-config-map.yaml