apiVersion: v1
kind: ConfigMap
metadata:
  name: file-system-ms-config-map
  namespace: notes-project
data:
  ROOT: "bin/root"
  ARCHIVE-ROOT: "bin/archive-root"
  RABBIT_MQ_HOST: rabbitmq-service
  RABBIT_MQ_USERNAME: guest
  RABBIT_MQ_PORT: "80"
  RABBIT_MQ_DESTINATION: filesystem.notifications.exchange
  DB_URL: file-system-ms-postgres-service
  DB_PORT: "80"
  DB_NAME: file_system
  DB_USERNAME: file_system_user
  KEYCLOAK_URL: keycloak-service
  KEYCLOAK_PORT: "80"
  CONFIG_SERVER_URL: config-server-service
  CONFIG_SERVER_PORT: "80"
  VAULT_HOST: vault-service
  VAULT_PORT: "80"
  VAULT_URL: "http://vault-service:80"
  VAULT_TOKEN: hvs.qbaI1DyLXYIwdBPzUYdBYo4m