apiVersion: v1
kind: ConfigMap
metadata:
  name: file-system-ms-config-map
data:
  ROOT: bin/root
  ARCHIVE-ROOT: bin/archive-root
  #RABBIT_MQ_HOST: rabbitmq-sandbox
  RABBIT_MQ_USERNAME: guest
  RABBIT_MQ_PORT: 5672
  RABBIT_MQ_DESTINATION: filesystem.notifications.exchange
  #DB_URL: file-system-ms-postgres-sandbox
  #DB_PORT: 5432
  DB_NAME: file_system
  DB_USERNAME: file_system_user
  KEYCLOAK_URL: keycloak-sandbox
  KEYCLOAK_PORT: 8080
  #CONFIG_SERVER_URL: config-server-sandbox
  #CONFIG_SERVER_PORT: 7777
  #VAULT_HOST: vault-sandbox
  VAULT_PORT: 8200
  #VAULT_URL: http://vault-sandbox:8200