apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config-map
  namespace: notes-project
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:80
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-host:9092
  KAFKA_LISTENERS: PLAINTEXT://:9092
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"