apiVersion: v1
kind: ConfigMap
metadata:
  name: logic-ms-config-map
  namespace: notes-project
data:
  CONFIG_SERVER_URL: config-server-service
  CONFIG_SERVER_PORT: "80"
  VAULT_HOST: vault-service
  VAULT_PORT: "80"
  VAULT_URL: http://vault-service:80
  OAUTH_HOST: registration-ms-service
  OAUTH_PORT: "80"
  RABBIT_HOST: rabbitmq-service
  RABBIT_PORT: "80"
  DB_HOST: logic-ms-postgres-service
  DB_PORT: "80"
  DB_NAME: logic_ms
  DB_USER: logic_ms_user
  KAFKA_HOST: kafka-broker-host
  KAFKA_PORT: "9092"
  RABBIT_EXCHANGE: filesystem.notifications.exchange
  KAFKA_TOPIC: additional.info.topic
  KAFKA_GROUP: logic.ms.group
  FILE_SYSTEM_HOST: file-system-ms-service
  FILE_SYSTEM_PORT: "80"
  USER_DATA_SYSTEM_HOST: user-data-system-ms-service
  USER_DATA_SYSTEM_PORT: "80"
  KEYCLOAK_HOST: keycloak-service
  KEYCLOAK_PORT: "80"
  KEYCLOAK_REALM: file-system-realm
  ALLOW_ORIGIN: "*"
  VAULT_TOKEN: hvs.qbaI1DyLXYIwdBPzUYdBYo4m
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"