apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config-map
  namespace: notes-project
data:
  rabbitmq.config: |
    [
      {rabbit, [
        {loopback_users, []}
      ]},
      {rabbitmq_management, [
        {load_definitions, "/etc/rabbitmq/definitions.json"}
      ]}
    ].
  definitions.json: |
    {
      "rabbit_version": "3.6.16",
      "users": [
        {
          "name": "guest",
          "password_hash": "eQmj8WIVsPivqyraOtikjbwxBk63L5PxCq4gWiglz6xsYsc7",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "parameters": [],
      "global_parameters": [
        {
          "name": "cluster_name",
          "value": "rabbit@e473b9a9542e"
        }
      ],
      "policies": [],
      "queues": [
        {
          "name": "filesystem.notifications.queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "exchanges": [
        {
          "name": "filesystem.notifications.exchange",
          "vhost": "/",
          "type": "topic",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "filesystem.notifications.exchange",
          "vhost": "/",
          "destination": "filesystem.notifications.queue",
          "destination_type": "queue",
          "routing_key": "#",
          "arguments": {}
        }
      ]
    }