apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-system-ms-config-map
  namespace: notes-project
data:
  CONFIG_SERVER_URL: config-server-service
  CONFIG_SERVER_PORT: "80"
  VAULT_HOST: vault-service
  VAULT_PORT: "80"
  VAULT_URL: http://vault-service:80
  DB_URL: registration-ms-postgres-service
  DB_PORT: "80"
  DB_NAME: registration_system
  DB_USER: registration_system_user
  DB_KAFKA_HOST: kafka-broker-host
  MAX_ACCESS_TOKEN_VALIDITY: "10000"
  MIN_ACCESS_TOKEN_VALIDITY: "10"
  MAX_REFRESH_TOKEN_VALIDITY: "10000"
  MIN_REFRESH_TOKEN_VALIDITY: "10"
  ALLOW_ORIGIN: "*"
  VAULT_TOKEN: hvs.RexMCDy6eT0z2uA5e8mQfQP8