apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-system-ms-config-map
data:
#  CONFIG_SERVER_URL: config-server-sandbox
#  CONFIG_SERVER_PORT: 7777
#  VAULT_HOST: vault-sandbox
#  VAULT_PORT: 8200
#  VAULT_URL: http://vault-sandbox:8200
#  DB_URL: registration-ms-postgres
#  DB_PORT: 5432
  DB_NAME: registration_system
  DB_USER: registration_system_user
  DB_KAFKA_HOST: kafka
  MAX_ACCESS_TOKEN_VALIDITY: 10000
  MIN_ACCESS_TOKEN_VALIDITY: 10
  MAX_REFRESH_TOKEN_VALIDITY: 10000
  MIN_REFRESH_TOKEN_VALIDITY: 10
  ALLOW_ORIGIN: "*"