apiVersion: v1
kind: ConfigMap
metadata:
  name: user-data-ms-config-map
  namespace: notes-project
data:
  CONFIG_SERVER_URL: config-server-service
  OAUTH_HOST: registration-ms-service
  OAUTH_PORT: "80"
  CONFIG_SERVER_PORT: "80"
  VAULT_HOST: vault-service
  VAULT_PORT: "80"
  VAULT_URL: http://vault-service:80
  DB_URL: user-data-ms-postgres-service
  DB_NAME: user_data_system
  DB_USER: personal_data_system_user
  KAFKA_HOST: kafka-broker-host
  RESTORE_PASSWORD_URL: "bscnotes.hopto.org/registration"
  VAULT_TOKEN: hvs.RexMCDy6eT0z2uA5e8mQfQP8
