apiVersion: v1
kind: ConfigMap
metadata:
  name: user-data-ms-config-map
data:
  CONFIG_SERVER_URL: config-server-sandbox
    #CONFIG_SERVER_PORT: 7777
    #VAULT_HOST: vault-sandbox
    #VAULT_PORT: 8200
    #VAULT_URL: http://vault-sandbox:8200
    DB_URL: user-data-ms-postgres
    DB_NAME: user_data_system
    DB_USER: personal_data_system_user
    KAFKA_HOST: kafka
    #CLUSTER_HOST: тут надо исправить на путь до ингресса