apiVersion: v1
kind: ConfigMap
metadata:
  name: user-data-ms-config-map
  namespace: notes-project
data:
  CONFIG_SERVER_URL: config-server-service
  CONFIG_SERVER_PORT: "80"
  VAULT_HOST: vault-service
  VAULT_PORT: "80"
  VAULT_URL: http://vault-service:80
  DB_URL: user-data-ms-postgres-service
  DB_NAME: user_data_system
  DB_USER: personal_data_system_user
  KAFKA_HOST: kafka-broker-host
  CLUSTER_HOST: "some-host-change-later"
  VAULT_TOKEN: hvs.qbaI1DyLXYIwdBPzUYdBYo4m